# Twitter API Information
Twitter:
  consumer_key: "vK9j4xVUc8YqQZvjeGbd3MAZt"
  consumer_secret: "7I3FQ4vjXk1yTyiAuDpTSpswNIFdYve3oVc5z7EFLgTnaEb7mw"
  access_token: "761891287-hM8E3Zr0cgTmSycqkjzwQnrkcLZM37PhIj2s7syR"
  access_token_secret: "ItzvtZllTJqs2YiNPZiGhoBGYwHvsYdQFqg5eHkPZ1tuf"